import Providers from "@/Providers/Providers";
import { AccessControl } from "accesscontrol";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ac = new AccessControl();

ac.grant("user")
  .createOwn(["book", "author", "wishlist", "favorite", "review"])
  .readOwn(["profile", "wishlist", "favorite", "book", "author"])
  .updateOwn(["profile", "review", "wishlist", "favorite", "book"])
  .deleteOwn(["profile", "review", "wishlist", "favorite", "book"])
  .grant("admin")
  .extend("user")
  .createAny(["book", "author", "review", "wishlist", "favorite"])
  .readAny(["profile", "book", "author", "review", "wishlist", "favorite"])
  .updateAny(["profile", "book", "author", "review", "wishlist", "favorite"])
  .deleteAny(["profile", "book", "author", "review", "wishlist", "favorite"]);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <Providers>{children}</Providers>
        <Toaster theme="dark" />
      </body>
    </html>
  );
}
